### ISSUE TITLE
Leveler not able to load. 

### ISSUE THREAD

**Issue by GreemDev** [AznStevy/Maybe-Useful-Cogs#40]
Here is the error I get in my console. 

ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it
[16/07/2017 19:02] ERROR red load_cogs 560: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "red.py", line 557, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\gr33m\OneDrive\Greem Bot\cogs\owner.py", line 899, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "C:\Users\gr33m\OneDrive\Greem Bot\cogs\leveler.py", line 2986, in setup
    n = Leveler(bot)
  File "C:\Users\gr33m\OneDrive\Greem Bot\cogs\leveler.py", line 60, in __init__
    dbs = client.database_names()
  File "lib\pymongo\mongo_client.py", line 1149, in database_names
    "listDatabases")["databases"]]
  File "lib\pymongo\database.py", line 491, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "C:\Users\gr33m\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "lib\pymongo\mongo_client.py", line 859, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "C:\Users\gr33m\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "lib\pymongo\mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "lib\pymongo\topology.py", line 214, in select_server
    address))
  File "lib\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it

Failed to load: cogs.leveler

If you could help, that'd be neat-o.

**Comment by AznStevy** [comment]
Please read the github page and use the (multiple) support servers linked both on the bot site and the cog site.

**Comment by GreemDev** [comment]
Here we are, (almost) 2 years later. Looking back on my GitHub history.

Good lord was I a moron.
Surprised you didn't lose it on me.
