### ISSUE TITLE
leveler, pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by skullbite** [AznStevy/Maybe-Useful-Cogs#48]
idk why this keeps happening, my bot won't load the cog can i please get help? here's my full traceback

``Traceback (most recent call last):
  File "/home/skullbite/red/cogs/owner.py", line 65, in load
    self._load_cog(module)
  File "/home/skullbite/redt/cogs/owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/home/skullbite/red/cogs/leveler.py", line 2989, in setup
    n = Leveler(bot)
  File "/home/skullbite/redt/cogs/leveler.py", line 63, in __init__
    dbs = client.database_names()
  File "lib/pymongo/mongo_client.py", line 1213, in database_names
    ("nameOnly", True)]))["databases"]]
  File "lib/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "lib/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "lib/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "lib/pymongo/topology.py", line 214, in select_server
    address))
  File "lib/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused``

**Comment by ChrisWhee1er** [comment]
Did you ever solve this issue?  I'm currently fighting the same fight ;P

> pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

Any advice?
