### ISSUE TITLE
Refused connection Error on load

### ISSUE THREAD

**Issue by ChrisWhee1er** [AznStevy/Maybe-Useful-Cogs#57]
I can't get it to load, and receive the following traceback call on the log:

> ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection cou
> ld be made because the target machine actively refused it
> [25/04/2018 15:46] ERROR red load_cogs 573: localhost:27017: [WinError 10061] No
>  connection could be made because the target machine actively refused it
> Traceback (most recent call last):
>   File "red.py", line 570, in load_cogs
>     owner_cog._load_cog(extension)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Red\cog
> s\owner.py", line 948, in _load_cog
>     self.bot.load_extension(mod_obj.__name__)
>   File "lib\discord\ext\commands\bot.py", line 738, in load_extension
>     lib.setup(self)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Red\cog
> s\leveler.py", line 3284, in setup
>     n = Leveler(bot)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Red\cog
> s\leveler.py", line 61, in __init__
>     dbs = client.database_names()
>   File "lib\pymongo\mongo_client.py", line 1496, in list_database_names
>     for doc in self.list_databases(session, nameOnly=True)]
>   File "lib\pymongo\mongo_client.py", line 1476, in list_databases
>     "admin").command(cmd, session=session)
>   File "lib\pymongo\database.py", line 529, in command
>     with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\con
> textlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "lib\pymongo\mongo_client.py", line 982, in _socket_for_reads
>     server = topology.select_server(read_preference)
>   File "lib\pymongo\topology.py", line 224, in select_server
>     address))
>   File "lib\pymongo\topology.py", line 183, in select_servers
>     selector, server_timeout, address)
>   File "lib\pymongo\topology.py", line 199, in _select_servers_loop
>     self._error_message(selector))
> pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No
>  connection could be made because the target machine actively refused it
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x0656E710>
> 
> Failed to load: cogs.

Sorry if this was previously mentioned, but I couldn't google myself out of this one.. ;< 
Help please and thanks for the awesome cog!

**Comment by Sinsae** [comment]
I got past that issue somehow and im retrieving a name does not exist error for 'fileIO'
